name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Wrangler
        run: npm install -g wrangler

      - name: Deploy a Cloudflare Pages
        run: wrangler pages deploy ./ --project-name=compritas-webstore
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}